on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v4.1.7
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        working-directory: src
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
